### Site Settings ###
title               : xin blog backend
description         : >-                               # >- means to ignore newlines until "url:"
                      Here is backend, just for personal use.
                      Please <a href=https://xinii.github.io/>go to homepage</a> of my blog.

url                 : "https://xinii.github.io"                               # base hostname & protocol for your site (e.g. http://example.com)
baseurl             : "/archive-site-b"                    # subpath of your site (e.g. /blog) [IMPORTANT: use "" if your are hosting at https://username.github.io directly]
repository          : https://github.com/xinii/    # repository metadata on GitHub Pages [know more at https://help.github.com/en/articles/repository-metadata-on-github-pages]
#remote_theme       : YoussefRaafatNasry/portfolYOU    # uncomment this if you are using it as a remote theme

### Author Info ###
author:
  name              : backend
  image             : https://raw.githubusercontent.com/xinii/blog/master/docs/xin.jpg
# behance           : your_username
# dribbble          : your_username
  email             : xinii@msn.com
  facebook          : xintxt
  github            : xinii
# gitlab            : your_username
# instagram         : your_username
  linkedin          : xinii
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : xintxt
# vimeo             : your_username
# youtube           : your_channel_name


### Pagination ###
paginate: 20
paginate_path: "/articles/page-:num/"


### Posts Permalink ###
permalink: articles/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


### Exclude from processing ###
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock
